### ISSUE TITLE
Reformat code structure

### ISSUE THREAD

**Issue by mikolajwichrowski** [mikolajwichrowski/swingding#11]
De code structuur is op het moment niet juist en dient gestructureerd te worden.
Zo moet alle god class zooi er uit en de logica naar de juiste klasse.

**Comment by mikolajwichrowski** [comment]
Deels gedaan. Handig om nog wel met z'n allen na te lopen en wat redundancy weg te halen. Ook moeten we nog kijken of dit er goed uit ziet in het klassen diagram

**Comment by TikoVergroesen** [comment]
Heb wat aan de positioning fedaan van het scherm, en heb ervoor gezorgd dat er nu ook buttons naast de panel op het JFrame kunnen staan.

**Comment by mikolajwichrowski** [comment]
Minimal refactoring done en codacy voor code quality toegevoegd
