### ISSUE TITLE
Klassen diagram

### ISSUE THREAD

**Issue by mikolajwichrowski** [mikolajwichrowski/swingding#12]
We moeten een klassen diagram hebben om de structuur mee op te frissen. 
#11 kan alleen worden afgemaakt als deze issue is opgelost.

**Comment by TikoVergroesen** [comment]
Ben er nu mee bezig, net als de documentatie die ernaar lijdt:
-Samenwerkingsovereenkomst
-Klein PvA
-Analyse & Design Klassendiagram
-Logic Matrix voor menu-progression

**Comment by Pawel-Zawada** [comment]
@Pawel-Zawada **TODO:** 

- [ ] Maak de klassendiagram op basis van de bestaande gegenereerde.
Let op dat er relaties zijn die pas worden geïnstantieerd tijdens runtime. Deze moeten in de code worden herkend.

**Comment by mikolajwichrowski** [comment]
Status op issue?
