### ISSUE TITLE
Unit test Grid movement

### ISSUE THREAD

**Issue by mikolajwichrowski** [mikolajwichrowski/swingding#13]
**TODO:**
- [ ] Schrijf unit tests @TikoVergroesen

_Originally posted by @Pawel-Zawada in https://github.com/mikolajwichrowski/swingding/issues/1#issuecomment-496635983_

**Comment by TikoVergroesen** [comment]
Unit tests voor deze requirement en "Player cannot move through walls" zijn gedaan. Issue is gesloten.
