### ISSUE TITLE
Multiple maps

### ISSUE THREAD

**Issue by mikolajwichrowski** [mikolajwichrowski/swingding#17]
in pauze menu optie geven om unieke map te spelen?

**Comment by mikolajwichrowski** [comment]
Misschien is het handiger om 1 spel te doen. Wel meerdere levels maken die uit een start en eind positie bestaan. Als je het level haalt speel je opnieuw in het eerste level (De kaarten kunnen we in json files opslaan)

**Comment by TikoVergroesen** [comment]
Ik kan tegelijkertijd ook ff kijken naar een menu enzo. Dit heeft wel voorrang.
