### ISSUE TITLE
Deuren openmaken met bijbehorende opgepakte sleutel

### ISSUE THREAD

**Issue by Pawel-Zawada** [mikolajwichrowski/swingding#5]
**Description**
Poppetje kan deuren open maken met een eerder opgepakte sleutel.

**Comment by Pawel-Zawada** [comment]
Kan #6  nodig hebben om de collisies tussen de gebruiker en de deur te hebben.

**Comment by mikolajwichrowski** [comment]
Collisies werken nu prima. Je moet eerst een sleutel opmaken voordat je een deur kan openmaken. De code is nu echter niet gestructureerd en dit moet eerst opgelost worden. Als we dit eenmaal goed hebben, kunnen we er voor zorgen dat sleutels alleen bijbehorende deuren open kunnen maken.

**Comment by mikolajwichrowski** [comment]
#11 en #12 moeten eerst opgelost zijn voordat we de sleutel functionaliteit kunnen uitbreiden.

**Comment by mikolajwichrowski** [comment]
Unit test voor de verschillende sleutels in verschillende deuren kan gemaakt worden.

**Comment by mikolajwichrowski** [comment]
Laatste versie werkt dit ook
